-- =============================================================================
-- GOLD LAYER: DIMENSIONAL STAR SCHEMA (OLAP)
-- =============================================================================
-- Target Schema: gold
-- Tables:
--   1. gold.dim_date
--   2. gold.dim_customer
--   3. gold.dim_product
--   4. gold.dim_seller
--   5. gold.dim_payment
--   6. gold.fact_sales
--
-- Notes on Metrics:
--   estimated_cost and estimated_profit are modeled proxy metrics:
--   - Estimated Product Cost = Price * 70% (30% benchmark gross product margin)
--   - Freight Handling Overhead = Freight Value * 15%
--   - Estimated Profit = Price - Estimated Product Cost - Freight Handling Overhead
--                      = (Price * 0.30) - (Freight Value * 0.15)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DROP EXISTING STAR SCHEMA OBJECTS (Preserving legacy summary tables)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS gold.fact_sales CASCADE;
DROP TABLE IF EXISTS gold.dim_payment CASCADE;
DROP TABLE IF EXISTS gold.dim_seller CASCADE;
DROP TABLE IF EXISTS gold.dim_product CASCADE;
DROP TABLE IF EXISTS gold.dim_customer CASCADE;
DROP TABLE IF EXISTS gold.dim_date CASCADE;

-- -----------------------------------------------------------------------------
-- 2. CREATE DIMENSION TABLES
-- -----------------------------------------------------------------------------

-- 2.1 DIM_DATE
CREATE TABLE gold.dim_date (
    date_key INTEGER PRIMARY KEY, -- YYYYMMDD
    full_date DATE NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    quarter_name VARCHAR(10) NOT NULL,
    month INTEGER NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    month_short VARCHAR(5) NOT NULL,
    day INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    day_name VARCHAR(20) NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    year_month VARCHAR(7) NOT NULL,
    year_quarter VARCHAR(10) NOT NULL
);

CREATE INDEX idx_dim_date_year_month ON gold.dim_date (year, month);

-- 2.2 DIM_CUSTOMER
CREATE TABLE gold.dim_customer (
    customer_key BIGSERIAL PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL UNIQUE,
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix VARCHAR(20),
    customer_city VARCHAR(100),
    customer_state VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_dim_customer_state ON gold.dim_customer (customer_state);
CREATE INDEX idx_dim_customer_city ON gold.dim_customer (customer_city);

-- 2.3 DIM_PRODUCT
CREATE TABLE gold.dim_product (
    product_key BIGSERIAL PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL UNIQUE,
    product_category_name VARCHAR(100),
    product_category_name_english VARCHAR(100),
    product_name_length INTEGER,
    product_description_length INTEGER,
    product_photos_qty INTEGER,
    product_weight_g NUMERIC,
    product_length_cm NUMERIC,
    product_height_cm NUMERIC,
    product_width_cm NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_dim_product_category ON gold.dim_product (product_category_name_english);

-- 2.4 DIM_SELLER
CREATE TABLE gold.dim_seller (
    seller_key BIGSERIAL PRIMARY KEY,
    seller_id VARCHAR(50) NOT NULL UNIQUE,
    seller_zip_code_prefix VARCHAR(20),
    seller_city VARCHAR(100),
    seller_state VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_dim_seller_state ON gold.dim_seller (seller_state);

-- 2.5 DIM_PAYMENT
CREATE TABLE gold.dim_payment (
    payment_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type VARCHAR(50) NOT NULL,
    payment_installments INTEGER NOT NULL DEFAULT 1,
    payment_installments_range VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_profile UNIQUE (payment_type, payment_installments)
);

-- -----------------------------------------------------------------------------
-- 3. CREATE FACT TABLE
-- -----------------------------------------------------------------------------
CREATE TABLE gold.fact_sales (
    sales_key BIGSERIAL PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    order_item_id INTEGER NOT NULL,
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer(customer_key),
    product_key BIGINT NOT NULL REFERENCES gold.dim_product(product_key),
    seller_key BIGINT NOT NULL REFERENCES gold.dim_seller(seller_key),
    date_key INTEGER NOT NULL REFERENCES gold.dim_date(date_key),
    payment_key BIGINT NOT NULL REFERENCES gold.dim_payment(payment_key),
    order_status VARCHAR(50),
    purchase_timestamp TIMESTAMP NOT NULL,
    shipping_limit_date TIMESTAMP,
    price NUMERIC(18,2) NOT NULL,
    freight_value NUMERIC(18,2) NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    estimated_cost NUMERIC(18,2) NOT NULL,
    estimated_profit NUMERIC(18,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fact_sales_item UNIQUE (order_id, order_item_id)
);

CREATE INDEX idx_fact_sales_date ON gold.fact_sales (date_key);
CREATE INDEX idx_fact_sales_customer ON gold.fact_sales (customer_key);
CREATE INDEX idx_fact_sales_product ON gold.fact_sales (product_key);
CREATE INDEX idx_fact_sales_seller ON gold.fact_sales (seller_key);
CREATE INDEX idx_fact_sales_payment ON gold.fact_sales (payment_key);
CREATE INDEX idx_fact_sales_order_status ON gold.fact_sales (order_status);

-- -----------------------------------------------------------------------------
-- 4. POPULATE DIMENSIONS FROM SILVER
-- -----------------------------------------------------------------------------

-- 4.1 Populate DIM_DATE (2016-01-01 to 2019-12-31)
INSERT INTO gold.dim_date (
    date_key,
    full_date,
    year,
    quarter,
    quarter_name,
    month,
    month_name,
    month_short,
    day,
    day_of_week,
    day_name,
    is_weekend,
    year_month,
    year_quarter
)
SELECT
    TO_CHAR(d, 'YYYYMMDD')::INTEGER AS date_key,
    d::DATE AS full_date,
    EXTRACT(YEAR FROM d)::INTEGER AS year,
    EXTRACT(QUARTER FROM d)::INTEGER AS quarter,
    'Q' || EXTRACT(QUARTER FROM d)::TEXT AS quarter_name,
    EXTRACT(MONTH FROM d)::INTEGER AS month,
    RTRIM(TO_CHAR(d, 'Month')) AS month_name,
    TO_CHAR(d, 'Mon') AS month_short,
    EXTRACT(DAY FROM d)::INTEGER AS day,
    EXTRACT(ISODOW FROM d)::INTEGER AS day_of_week,
    RTRIM(TO_CHAR(d, 'Day')) AS day_name,
    CASE WHEN EXTRACT(ISODOW FROM d) IN (6, 7) THEN TRUE ELSE FALSE END AS is_weekend,
    TO_CHAR(d, 'YYYY-MM') AS year_month,
    TO_CHAR(d, 'YYYY') || '-Q' || EXTRACT(QUARTER FROM d)::TEXT AS year_quarter
FROM GENERATE_SERIES('2016-01-01'::DATE, '2019-12-31'::DATE, '1 day'::INTERVAL) d;

-- 4.2 Populate DIM_CUSTOMER
INSERT INTO gold.dim_customer (
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix,
    customer_city,
    customer_state
)
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix,
    customer_city,
    customer_state
FROM silver.customers
ORDER BY customer_id;

-- 4.3 Populate DIM_PRODUCT (With English translations from bronze.category_translation_raw)
INSERT INTO gold.dim_product (
    product_id,
    product_category_name,
    product_category_name_english,
    product_name_length,
    product_description_length,
    product_photos_qty,
    product_weight_g,
    product_length_cm,
    product_height_cm,
    product_width_cm
)
SELECT
    p.product_id,
    p.product_category_name,
    INITCAP(REPLACE(COALESCE(t.product_category_name_english, p.product_category_name, 'Other'), '_', ' ')) AS product_category_name_english,
    p.product_name_length,
    p.product_description_length,
    p.product_photos_qty,
    p.product_weight_g,
    p.product_length_cm,
    p.product_height_cm,
    p.product_width_cm
FROM silver.products p
LEFT JOIN (
    SELECT DISTINCT
        LOWER(product_category_name) AS product_category_name,
        product_category_name_english
    FROM bronze.category_translation_raw
) t ON LOWER(p.product_category_name) = t.product_category_name
ORDER BY p.product_id;

-- 4.4 Populate DIM_SELLER
INSERT INTO gold.dim_seller (
    seller_id,
    seller_zip_code_prefix,
    seller_city,
    seller_state
)
SELECT
    seller_id,
    seller_zip_code_prefix,
    seller_city,
    seller_state
FROM silver.sellers
ORDER BY seller_id;

-- 4.5 Populate DIM_PAYMENT
-- Insert standard default unknown row
INSERT INTO gold.dim_payment (
    payment_key,
    payment_type,
    payment_installments,
    payment_installments_range
)
OVERRIDING SYSTEM VALUE
VALUES (0, 'UNKNOWN', 1, 'Not Applicable');

-- Insert distinct combinations from silver.payments
INSERT INTO gold.dim_payment (
    payment_type,
    payment_installments,
    payment_installments_range
)
SELECT
    payment_type,
    payment_installments,
    CASE
        WHEN payment_installments = 1 THEN '1 Installment'
        WHEN payment_installments BETWEEN 2 AND 3 THEN '2-3 Installments'
        WHEN payment_installments BETWEEN 4 AND 6 THEN '4-6 Installments'
        WHEN payment_installments >= 7 THEN '7+ Installments'
        ELSE '1 Installment'
    END AS payment_installments_range
FROM (
    SELECT DISTINCT
        COALESCE(payment_type, 'UNKNOWN') AS payment_type,
        GREATEST(1, COALESCE(payment_installments, 1)) AS payment_installments
    FROM silver.payments
) p
ON CONFLICT (payment_type, payment_installments) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 5. POPULATE FACT TABLE (FACT_SALES)
-- -----------------------------------------------------------------------------
WITH primary_order_payment AS (
    SELECT DISTINCT ON (order_id)
        order_id,
        COALESCE(payment_type, 'UNKNOWN') AS payment_type,
        GREATEST(1, COALESCE(payment_installments, 1)) AS payment_installments
    FROM silver.payments
    ORDER BY order_id, payment_value DESC, payment_sequential ASC
)
INSERT INTO gold.fact_sales (
    order_id,
    order_item_id,
    customer_key,
    product_key,
    seller_key,
    date_key,
    payment_key,
    order_status,
    purchase_timestamp,
    shipping_limit_date,
    price,
    freight_value,
    total_amount,
    quantity,
    estimated_cost,
    estimated_profit
)
SELECT
    f.order_id,
    f.order_item_id,
    c.customer_key,
    p.product_key,
    s.seller_key,
    TO_CHAR(f.purchase_timestamp, 'YYYYMMDD')::INTEGER AS date_key,
    COALESCE(pay.payment_key, 0) AS payment_key,
    f.order_status,
    f.purchase_timestamp,
    f.shipping_limit_date,
    f.price,
    f.freight_value,
    ROUND(f.price + f.freight_value, 2) AS total_amount,
    1 AS quantity,
    ROUND((f.price * 0.70) + (f.freight_value * 0.15), 2) AS estimated_cost,
    ROUND((f.price * 0.30) - (f.freight_value * 0.15), 2) AS estimated_profit
FROM silver.order_fact f
JOIN gold.dim_customer c ON f.customer_id = c.customer_id
JOIN gold.dim_product p ON f.product_id = p.product_id
JOIN gold.dim_seller s ON f.seller_id = s.seller_id
LEFT JOIN primary_order_payment pop ON f.order_id = pop.order_id
LEFT JOIN gold.dim_payment pay ON pop.payment_type = pay.payment_type AND pop.payment_installments = pay.payment_installments;
